//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coustmer
    {
        public Coustmer()
        {
            this.Hisories = new HashSet<Hisory>();
        }
    
        public string U_Name { get; set; }
        public int U_ID { get; set; }
        public string U_email { get; set; }
        public string U_image { get; set; }
        public string U_password { get; set; }
        public string U_Manger { get; set; }
    
        public virtual ICollection<Hisory> Hisories { get; set; }
    }
}
