//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hisory
    {
        public int id { get; set; }
        public string date { get; set; }
        public int price { get; set; }
        public string P_name { get; set; }
        public string p_image { get; set; }
        public int U_ID { get; set; }
        public int P_ID { get; set; }
    
        public virtual Coustmer Coustmer { get; set; }
        public virtual Product Product { get; set; }
    }
}
