//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodApplication.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Hisories = new HashSet<Hisory>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_image { get; set; }
        public int P_price { get; set; }
    
        public virtual ICollection<Hisory> Hisories { get; set; }
    }
}
